## [1] Use the UNPIVOT operation to convert columns into rows for subsequent left-joined feature creation.
SELECT DISTINCT *
FROM
(
    SELECT CASE_NO,
           CUSTOMER_ID,
           FORMAT(CAST(APPROVAL_DATE AS DATE), 'yyyyMM') AS APPROVAL_MON,
           FORMAT(CAST(LOAN_START_DATE AS DATE), 'yyyyMM') AS LOAN_START_MON,
           FORMAT(DATEADD(MONTH, 3, CAST(LOAN_START_DATE AS DATE)), 'yyyyMM') AS LOAN_START_MON_3
    FROM (
            SELECT CASE_NO,
                   CUSTOMER_ID,
                   MIN(LOAN_START_DATE) AS LOAN_START_DATE,
                   MIN(APPROVAL_DATE) AS APPROVAL_DATE
            FROM TB_LOAN_STATEMENT
            WHERE SUBSTRING(CUSTOMER_ID, 2, 1) NOT LIKE '[A-Z]%'
            GROUP BY CASE_NO, CUSTOMER_ID
         ) BASE
    WHERE DATEDIFF(MONTH, LOAN_START_DATE, '1900-01-01') >= 3
    GROUP BY CASE_NO, CUSTOMER_ID, LOAN_START_DATE, APPROVAL_DATE
) A
UNPIVOT
(
    MONTH_VAL FOR MONTH_NAME IN (LOAN_START_MON, LOAN_START_MON_3)
) AS UNPVT;


## [2] Retrieve previous period values within each case sequence.
SELECT CASE_NO
      ,CUSTOMER_ID
      ,LAG(MONTH_VAL, 1, NULL) OVER (PARTITION BY CASE_NO ORDER BY MONTH_VAL) AS START_MONTH
      ,LAG(CLASS_WM, 1, NULL) OVER (PARTITION BY CASE_NO ORDER BY MONTH_VAL) AS START_CLASS
      ,MONTH_VAL AS LAST_MONTH
      ,CLASS_WM AS LAST_CLASS
FROM TMP_CASE_LIST;


## [3] Use prime numbers to group text categories (e.g. District)
DROP TABLE IF EXISTS TB_COLL_INFO;
SELECT  CASE_NO
       ,COLL_ID
       ,CASE 
            WHEN AVG(REGION_CODE) = 7  THEN 'NORTH'
            WHEN AVG(REGION_CODE) = 11 THEN 'CENTRAL'
            WHEN AVG(REGION_CODE) = 13 THEN 'SOUTH'
            WHEN AVG(REGION_CODE) = 17 THEN 'EAST'
            WHEN AVG(REGION_CODE) = 19 THEN 'ISLAND'
       END AS REGION
INTO TB_COLL_INFO
FROM 
(
    SELECT A.CASE_NO
          ,A.COLL_ID
          ,CASE 
                WHEN SUBSTRING(B.REGION_NAME, 1, 2) IN ('AA','BB','CC') THEN 7
                WHEN SUBSTRING(B.REGION_NAME, 1, 2) IN ('DD','EE') THEN 11
                WHEN SUBSTRING(B.REGION_NAME, 1, 2) IN ('FF','GG','HH') THEN 13
                WHEN SUBSTRING(B.REGION_NAME, 1, 2) IN ('II') THEN 17
                WHEN SUBSTRING(B.REGION_NAME, 1, 2) IN ('JJ','KK','LL') THEN 19
           END AS REGION_CODE
    FROM TB_CASE_COLLECTION A
    LEFT JOIN (SELECT * FROM TB_REGION_CODE WHERE CODE_TYPE = 'REGION')B
    ON A.CITY_CODE = B.CODE_ID
)E
GROUP BY CASE_NO;


## [4] Use WHILE loop to generates a sequence of monthly periods by iterating backward in time from the current month
DECLARE  
@TOTAL_NUM INT,  
@NUM INT,       
@MONTH_VAL VARCHAR(6);

SET @TOTAL_NUM = -61; 
SET @NUM = -4;        

WHILE @NUM >= @TOTAL_NUM  
BEGIN
    SET @MONTH_VAL = FORMAT(DATEADD(MONTH, @NUM, GETDATE()), 'yyyyMM');
    
	INSERT TB_MONTH_SEQ ([MONTH_VAL]) VALUES (@MONTH_VAL);
    
	SET @NUM = @NUM - 1;
END;


## [5] Use WINDOW FUNCTION to compute 1-, 3-, and 6-month rolling transaction sums
DROP TABLE IF EXISTS TB_CUST_TIME_BASE;
SELECT *
INTO TB_CUST_TIME_BASE
FROM TB_MONTH_SEQ, 
     (SELECT CASE_NO, CUSTOMER_ID, START_MONTH FROM TB_CASE_LIST) BASE;

DROP TABLE IF EXISTS TMP_TRX_WM;
SELECT A.MONTH_VAL
       ,A.CASE_NO
       ,A.CUSTOMER_ID
       ,A.START_MONTH
       ,ISNULL(B.TRX_VOLUME, 0) AS TRX_VOL
       ,CASE WHEN ISNULL(B.TRX_VOLUME, 0) > 0 THEN 1 ELSE 0 END AS HAS_NEW_TRX
INTO TMP_TRX_WM
FROM TB_CUST_TIME_BASE A
LEFT JOIN (
            SELECT [MONTH] AS TRX_MONTH
                   ,CUSTOMER_ID
                   ,SUM(VOLUME) AS TRX_VOLUME
            FROM TB_WM_TRANSACTION
            GROUP BY [MONTH], CUSTOMER_ID
            HAVING CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM TMP_CASE_LIST)
          ) B
ON A.CUSTOMER_ID = B.CUSTOMER_ID AND A.MONTH_VAL = B.TRX_MONTH;



DROP TABLE IF EXISTS TB_TRX_FEATURES;
SELECT MONTH_VAL,
       CUSTOMER_ID,
       CASE_NO,
       SUM(TRX_VOL) OVER (PARTITION BY CUSTOMER_ID, CASE_NO ORDER BY MONTH_VAL ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS TRX_AMT_1M,
       SUM(TRX_VOL) OVER (PARTITION BY CUSTOMER_ID, CASE_NO ORDER BY MONTH_VAL ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING) AS TRX_AMT_3M,
       SUM(TRX_VOL) OVER (PARTITION BY CUSTOMER_ID, CASE_NO ORDER BY MONTH_VAL ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) AS TRX_AMT_6M
INTO TB_TRX_FEATURES
FROM TMP_TRX_WM;




