--######### 1. Matching future target labels to customers at specific months  #######--
--#Generate a list of statement months for the observation period.

-- Create the month sequence table
DROP TABLE IF EXISTS STMT_MON_SEQ;
CREATE TABLE STMT_MON_SEQ ([STMT_MON] VARCHAR(6));

DECLARE  
    @TotalNum INT,  
    @Num INT,       
    @STMT_MON VARCHAR(6);

-- Set loop parameters
SET @TotalNum = -27;  -- Total number of months to go back
SET @Num = -1;        -- Start from last month

-- Generate month sequence
WHILE @Num >= @TotalNum
BEGIN
    SET @STMT_MON = FORMAT(DATEADD(MONTH, @Num, GETDATE()), 'yyyyMM');
    INSERT INTO STMT_MON_SEQ ([STMT_MON]) VALUES (@STMT_MON);
    SET @Num = @Num - 1;
END;


--#For each customer, label whether they have the product in the next period.
DROP TABLE IF EXISTS R_XSELL_PL_CUST_LIST_VAR
SELECT *
        -- Use next month's YN_PL as Y_FLAG
       ,CASE WHEN LEAD(YN_PL, 1, NULL) OVER (PARTITION BY ACCT_NBR  ORDER BY STMT_MON ASC) IS NULL THEN YN_PL
			 ELSE LEAD(YN_PL, 1, NULL) OVER (PARTITION BY ACCT_NBR  ORDER BY STMT_MON ASC) END AS  Y_FLAG 
INTO R_XSELL_PL_CUST_LIST_VAR
FROM 
(
	SELECT  A.ACCT_NBR
		   ,STMT_MON
		   ,CC_START_MON
		   ,RPL_START_MON
		   ,PL_START_MON
		   ,CASE WHEN (STMT_MON>=C_START_MON) THEN 1 ELSE 0 END AS YN_CC
		   ,CASE WHEN (STMT_MON>=R_START_MON) THEN 1 ELSE 0 END AS YN_RPL
		   ,CASE WHEN (STMT_MON>=P_START_MON) THEN 1 ELSE 0 END AS YN_PL
	FROM
	(
		SELECT ACCT_NBR, STMT_MON 
		FROM R_XSELL_PL_CUST_LIST , STMT_MON_SEQ 
	)A
	LEFT JOIN R_XSELL_PL_CUST_LIST B
	ON A.ACCT_NBR=B.ACCT_NBR
)C


--######### 2. Deriving rolling-window features over 1M, 3M, 6M, and 12M periods #######--
--#e.g. : Derive rolling ratios of revolving balance to statement balance
DROP TABLE IF EXISTS CREDITCARD_CUSTOMER_FEATURES
SELECT  ACCT_NBR
       ,STMT_MON
	   ,CC_START_MON
	   ,RPL_START_MON
	   ,PL_START_MON
	   ,YN_CC
	   ,YN_RPL
	   ,YN_PL
	   ,Y_FLAG 
		-- Revolving balance as proportion of total statement balance
       ,SUM_REVOL_BAL_1M/(CASE WHEN SUM_STMT_BAL_1M=0 THEN 1 ELSE SUM_STMT_BAL_1M END) AS AVG_REVOL_BAL_PRT_1M
       ,SUM_REVOL_BAL_3M/(CASE WHEN SUM_STMT_BAL_3M=0 THEN 1 ELSE SUM_STMT_BAL_3M END) AS AVG_REVOL_BAL_PRT_3M
	   ,SUM_REVOL_BAL_6M/(CASE WHEN SUM_STMT_BAL_6M=0 THEN 1 ELSE SUM_STMT_BAL_6M END) AS AVG_REVOL_BAL_PRT_6M
	   ,SUM_REVOL_BAL_12M/(CASE WHEN SUM_STMT_BAL_12M=0 THEN 1 ELSE SUM_STMT_BAL_12M END) AS AVG_REVOL_BAL_PRT_12M
INTO CREDITCARD_CUSTOMER_FEATURES
FROM
(
SELECT  A.*
	   -- Rolling statement balance totals
	   ,SUM(A.STMT_BAL) OVER (PARTITION BY ACCT_NBR ORDER BY STMT_MON  ROWS BETWEEN 0 PRECEDING AND CURRENT ROW) AS SUM_STMT_BAL_1M
       ,SUM(A.STMT_BAL) OVER (PARTITION BY ACCT_NBR ORDER BY STMT_MON  ROWS BETWEEN 2 PRECEDING AND CURRENT ROW ) AS SUM_STMT_BAL_3M
	   ,SUM(A.STMT_BAL) OVER (PARTITION BY ACCT_NBR ORDER BY STMT_MON  ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS SUM_STMT_BAL_6M
	   ,SUM(A.STMT_BAL) OVER (PARTITION BY ACCT_NBR ORDER BY STMT_MON  ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS SUM_STMT_BAL_12M
	   	-- Rolling revolving balance totals
	   ,SUM(A.REVOL_BAL) OVER (PARTITION BY ACCT_NBR ORDER BY STMT_MON  ROWS BETWEEN 0 PRECEDING AND CURRENT ROW) AS SUM_REVOL_BAL_1M
       ,SUM(A.REVOL_BAL) OVER (PARTITION BY ACCT_NBR ORDER BY STMT_MON  ROWS BETWEEN 2 PRECEDING AND CURRENT ROW ) AS SUM_REVOL_BAL_3M
	   ,SUM(A.REVOL_BAL) OVER (PARTITION BY ACCT_NBR ORDER BY STMT_MON  ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS SUM_REVOL_BAL_6M
	   ,SUM(A.REVOL_BAL) OVER (PARTITION BY ACCT_NBR ORDER BY STMT_MON  ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS SUM_REVOL_BAL_12M
FROM TMP_CREDITCARD_BILLING_BASE  A
)B
